### ISSUE TITLE
Integrity Error while importing old data in trade dangerous

### ISSUE THREAD

**Issue by Ayexor** [Ayexor/Trade-Dangerous#1]
@https://github.com/Ayexor/MathSem_Presentation/issues/1 was generated in another repo, since issues were not activated here.

`sqlite3.IntegrityError: UNIQUE constraint failed: System.name` indicates that the plugin is trying to create a system that already exists. But I have never used the eddblink plugin, so not sure if I can be of help.

The plugin also uses its own function for creating new systems, instead of the `tdb.addLocalSystem()` from the TradeDB class. Maybe this is outdated in this fork.

In this fork, the TradeDB class has been changed so that the prices files are not used anymore, but instead the data only resides in the SQLite3 database, previously only used as cache. (And I was too lazy to update the docs / comments / readmes.)

When I forked this project, there was no usable public data source, so I wrote the `tradedangerous/eddn_connector.py`, which collects the data directly from the EDDN, creating missing systems, stations and items on the fly. No need to import (possibly outdated) data. Downside: eddn_connector.py needs to run continouosly as to not miss data from EDDN.

**Comment by tdroenner** [comment]
Maybe you can change it, that the base import works. Therefore you don't have to wait until it fills up with EDDN and some outdated data is available. How can I run the eddn_connector to collect the data?

**Comment by Ayexor** [comment]
I'll have a look at the plugin and see what I can do in reasonable time.

The `eddn_connector.py` is an executable script. Simply run it in your favourite python shell.

I run it on a separate server, so it is constantly connected to EDDN. For accessing the data, I copy `./data/TradeDangerous.db` from the server over to my pc.

**Comment by Ayexor** [comment]
The data itself is inconsistent: multiple IDs for the same system name. This gets remapped according to the system name but consistency cannot be guaranteed. Use cautiously.

I also added an option to skip fleet carriers. The 'latest' data is more than five months old and most fleet carriers will probably haved moved by now.

The plugin now imports the data as needed, use `trade import -P eddblink -O solo,skipvend,skipFleet`.

The `solo` option skips import of prices and can be omitted if one wants to import 1.6 GB of outdated und practically useless data. Mind however that running `eddn_connector.py` will purge all price data older then 14 days. (Can be changed of course but currently hard coded.)

In case you want more up to date data, you can download a snapshot of mine here: https://drive.google.com/file/d/1Ds2l2HOT3RCLzb6nHlmo77XbxuuOSUel/view?usp=sharing
This is certainly consistend and up to date. Simply copy the db into `data/` and get going.
Don't forget to keep your data up to date by having `eddn_connector.py` running all the time. ;-)

**Comment by tdroenner** [comment]
Import is working. Thank you for fixing it. I've downloaded your TradeDangerous.db. I'll try running the eddn_connector on a server in my local lan. Maybe I can get it working. Don't know if I have to adjust the firewall.

**Comment by Ayexor** [comment]
You're welcome. I'm happy that my script is of use to others, too. And now that issues are activated, just open a new one if need be.

It is the server who connects to EDDN, so `eddn_connector` creates an outgoing connection. It would be a very restrictive firewall if outgoing connections were blocked.

**Comment by tdroenner** [comment]
I've tried to launch it. I get the following error:
:~/Trade-Dangerous/tradedangerous$ ./eddn_connector.py
Traceback (most recent call last):
  File "/home/tdroenner/Trade-Dangerous/tradedangerous/./eddn_connector.py", line 10, in <module>
    from tradedangerous.tradeenv import TradeEnv
ModuleNotFoundError: No module named 'tradedangerous'

I'm not the Python master. Java and PHP are more my "thing". Do you have a suggestion?
pip install tradedangerous solves it, but the old version is installed.

**Comment by Ayexor** [comment]
When installing via `pip install` the files are locally copied. If you change the file, you have to run the install command again.
If you want to change the files without the need for re-insall you can create an 'editable install' with `pip install -e`, which does not copy any files but used the original files directly. 

See https://pip.pypa.io/en/stable/topics/local-project-installs/ for more infos on installs.

(I admit I never really understood how path resolution works in python. Maybe I am missing somethin in the __init__.py files. But when installed via `pip install [-e]`, it runs fine on my side. Hope it works for you, too.)
